name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      couchdb:
        image: couchdb:latest
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: admin                  
          COUCHDB_PASSWORD: pass                  
        options: >-
          --health-cmd "curl -X GET http://couchdb:5984/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Create the test database
        run: |
          apt-get update
          apt-get install -y curl
          curl -X PUT http://admin:pass@couchdb:5984/test
      - name: Run unit tests with nose
        run: nosetests
        env:
          BINDING_CLOUDANT: '{"username":"admin","password":"pass","host":"couchdb","port":5984,"url":"http://admin:pass@couchdb:5984"}'

      - name: Upload code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
         version: "v0.1.13"
